FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04

# for clang installation
RUN sudo apt -y install lsb-release wget software-properties-common gnupg
RUN wget https://apt.llvm.org/llvm.sh
RUN chmod a+x llvm.sh
RUN sudo ./llvm.sh 20

RUN sudo apt -y install libomp-20-dev # required when using clang instead of g++
RUN sudo apt -y install libc++-20-dev libc++abi-20-dev

ARG REINSTALL_CMAKE_VERSION_FROM_SOURCE="3.31.6"

# Optionally install the cmake for vcpkg
COPY ./reinstall-cmake.sh /tmp/

RUN if [ "${REINSTALL_CMAKE_VERSION_FROM_SOURCE}" != "none" ]; then \
        chmod +x /tmp/reinstall-cmake.sh && /tmp/reinstall-cmake.sh ${REINSTALL_CMAKE_VERSION_FROM_SOURCE}; \
    fi \
    && rm -f /tmp/reinstall-cmake.sh

# [Optional] Uncomment this section to install additional vcpkg ports.
# RUN su vscode -c "${VCPKG_ROOT}/vcpkg install <your-port-name-here>"

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
RUN sudo apt update && sudo apt -y install cmake-curses-gui python3-dev  python3-pip  python3.12-venv #  python3-build
# RUN python3 -m venv .venv && . .venv/bin/activate
RUN python3 -m pip install  --break-system-packages cppyy==3.1.2 # for python bindings
# or use --prefix=/usr/local and
# ENV PYTHONPATH="/usr/local/lib/python3.X/site-packages:$PYTHONPATH"

#RUN sudo apt -y install libboost-all-dev
RUN sudo wget -P  /usr/local/boost https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2
RUN tar --bzip2 -xf /usr/local/boost/boost_1_87_0.tar.bz2 -C /usr/local/boost
ENV Boost_DIR=/usr/local/boost/boost_1_87_0

# for PyViz visualization
RUN sudo apt -y install gir1.2-goocanvas-2.0 python3-gi python3-gi-cairo python3-pygraphviz gir1.2-gtk-3.0 ipython3

RUN sudo apt -y install sqlite3 libsqlite3-dev

# NetAnim
# RUN sudo apt -y install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools


RUN sudo apt -y install libeigen3-dev

RUN sudo apt -y install gsl-bin libgsl-dev libgslcblas0

#DPDK dependencies
#RUN sudo apt -y dpdk-igb-uio-dkms # only available up to ubuntu 20.04 not later
# RUN sudo apt -y install dpdk dpdk-dev libdpdk-dev

RUN sudo apt -y install lxc-utils lxc-templates vtun uml-utilities ebtables bridge-utils

RUN git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && sudo ./bootstrap-vcpkg.sh && sudo ./vcpkg integrate install && sudo ./vcpkg install range-v3

#&& python3 -m pip install -r requirements.txt
#RUN git clone https://github.com/jbeder/yaml-cpp.git /workspaces/scion-simulator-master/src/scion/include/yaml-cpp
#RUN mkdir /workspaces/scion-simulator-master/src/scion/include/yaml-cpp/build && cd /workspaces/scion-simulator-master/src/scion/include/yaml-cpp/build && cmake ../ && make
# for clang and clang++
ENV PATH=$PATH:/usr/lib/llvm-20/bin
ENV YAML_CPP_INCLUDE_PATH=src/scion/include/yaml-cpp/include/
ENV YAML_CPP_LIBRARY_PATH=/workspaces/scion-simulator-master/src/scion/include/yaml-cpp/build
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/workspaces/scion-simulator-master/src/scion/include/yaml-cpp/build
ENV CC=clang-20
ENV CXX=clang++-20