//
// Copyright (c) 2006 Georgia Tech Research Corporation
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation;
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// Author: 

#ifndef SCION_L4_PROTOCOL_H
#define SCION_L4_PROTOCOL_H

#include "ns3/ipv4-l4-protocol.h"
#include "ipv4-header.h"
#include "ipv6-header.h"

#include "ns3/callback.h"
#include "ns3/object.h"

namespace ns3
{

class Packet;
class SCIONAddress;
class SCIONInterface;
class SCIONRoute;

/**
 * \ingroup internet
 *
 * \brief L4 Protocol abstract base class.
 *
 * This is an abstract base class for layer four protocols which use SCION as
 * the network layer.
 */
class SCIONL4Protocol : public IpL4Protocol
{
  public:
    

    /**
     * \brief Get the type ID.
     * \return the object TypeId
     */
    static TypeId GetTypeId();

    ~SCIONL4Protocol() override;

    /**
     * \brief Returns the protocol number of this protocol.
     * \returns the protocol number.
     */
    virtual int GetProtocolNumber() const = 0;

    /**
     * \brief Called from lower-level layers to send the packet up in the stack.
     * \param p packet to forward up
     * \param header IPv4 Header information
     * \param incomingInterface the Ipv4Interface on which the packet arrived
     * \returns Rx status code
     */
    virtual RxStatus Receive(Ptr<Packet> p,
                             const SCIONHeader& header,
                             Ptr<SCIONInterface> incomingInterface) = 0;

   


    /**
     * \brief Called from lower-level layers to send the ICMPv6 packet up in the stack.
     * \param icmpSource the source address of the icmp message
     * \param icmpTtl the ttl of the icmp message
     * \param icmpType the 'type' field of the icmp message
     * \param icmpCode the 'code' field of the icmp message
     * \param icmpInfo extra information dependent on the icmp message
     *        generated by Icmpv6L4Protocol
     * \param payloadSource the source address of the packet which triggered
     *        the icmp message
     * \param payloadDestination the destination address of the packet which
     *        triggered the icmp message.
     * \param payload the first 8 bytes of the packet payload
     *        which triggered the icmp message.
     */
    virtual void ReceiveScmp(SCIONAddress scmpSource,
                             uint8_t scmpTtl,
                             uint8_t scmpType,
                             uint8_t scmpCode,
                             uint32_t scmpInfo,
                             SCIONAddress payloadSource,
                             SCIONAddress payloadDestination,
                             const uint8_t payload[8]);

    /**
     * \brief callback to send packets over SCION
     */
    typedef Callback<void, Ptr<Packet>, SCIONAddress, SCIONAddress, uint8_t, Ptr<SCIONRoute>>   DownTargetCallbackSCION;

    /**
     * This method allows a caller to set the current down target callback
     * set for this L4 protocol
     *
     * \param cb current Callback for the L4 protocol
     */
    virtual void SetDownTargetSCION(DownTargetCallbackSCION cb) = 0;


    /**
     * This method allows a caller to get the current down target callback
     * set for this L4 protocol
     *
     * \return current Callback for the L4 protocol
     */
    virtual DownTargetCallbackSCION GetDownTargetSCION() const = 0;

};

} // Namespace ns3

#endif
